{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chat-bot.fullname" . }}-backend
  labels:
    {{- include "todo-chat-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chat-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
